### ISSUE TITLE
Issue on page /docs/e_interpolation.html

### ISSUE THREAD

**Issue by eduardofhenty** [mmann1123/pyGIS#13]
I am a geophysicist and meteorologist from USP. I'm trying to understand how to do the interpolation by krikigem. The difficulty is where to find the shapefile of the rainfall. By the indicated link https://earthworks.stanford.edu/catalog/stanford-td754wr4701 I could not find it.

**Comment by mmann1123** [comment]
We generated the points by extracting the raster values to random points 

# Rainfall measurement "locations"
# Source: https://earthworks.stanford.edu/catalog/stanford-td754wr4701
# Modified by author by clipping raster to San Francisco Bay Area, generating random points, and extracting raster values (0-255) to the points
rainfall = gpd.read_file("../_static/e_vector_shapefiles/sf_bay_rainfall/sf_bay_rainfall.shp")
