### ISSUE TITLE
Issue on page /docnumpy.core._exceptions._ArrayMemoryError: Unable to allocate 14.3 MiB for an array with shape (1621, 2308) and data type float32s/e_raster_window_operations.html

### ISSUE THREAD

**Issue by dsys2003** [mmann1123/pyGIS#14]
Your issue content here.

**Comment by mmann1123** [comment]
@dsys2003 I need a little more detail here. Is the issue that you can't replicate one of the examples on your computer and are running into memory issues?  If so please let me know what example is throwing the error, maybe I can give some suggestions.
