### ISSUE TITLE
Issue on page /docs/b_python_by_example.html

### ISSUE THREAD

**Issue by rfpg** [mmann1123/pyGIS#25]
You mention data structures: will students need a refresher on what a data structure actually is? In Python, you're usually talking about data frames but data structures is a broad topic in CS and can mean a whole host of different things, so I'd recommend that you include at least one resource that presents data structures as they relate to your course so the students know what you mean, what they look like, why they matter and how they'll be used. Especially since their prior Python experience may not have included exposure to data structures (although most generally do).  

I'd also recommend that you move the comment on indentation to the Getting Started With Python section. What Python looks like and how it operates should probably be clear before students start to work with your code examples.

**Comment by mmann1123** [comment]
Added section on data structures and an intro to the use of indentation.
