### ISSUE TITLE
Issue on page /docs/c_features.html

### ISSUE THREAD

**Issue by rfpg** [mmann1123/pyGIS#31]
I recommend that you relabel the Review section to "Spatial Data" as opposed to "Data Structures" or include more detail about data structures in the former incl., the definition in this section. In fact, it might make more sense to move your Data Structure definition here into the Spatial Data section. It seems a bit odd to define these in a subsequent section after the initial example was given two sections ago.

I recommend that you provide more context around your examples, including _why_ you're showing them naturalearth_lowres, etc.

**Comment by mmann1123** [comment]
Is this supposed to be for `c_vectors`?  I think so . 

Adding more context and linking back to earlier intro more clearly.
