### ISSUE TITLE
Issue on page /docs/c_new_vectors.html

### ISSUE THREAD

**Issue by rfpg** [mmann1123/pyGIS#32]
I like the objectives! CSV should probably be uppercase and I'd recommend spelling out latitude and longitude at least one time before abbreviating each word. Or highlight the fact this is GeoSpat / Pythonic language. Otherwise, it might be confusing to some learners.

**Comment by mmann1123** [comment]
Thanks for leaving all these comments! I will take them on in a bit.

**Comment by rfpg** [comment]
Sure! Should get to Module 2 today, too. If not, tomorrow!
