### ISSUE TITLE
Issue on page /docs/f_rs_config.html

### ISSUE THREAD

**Issue by rfpg** [mmann1123/pyGIS#52]
Sub out "understand" in the third learning objective. 

Another (debatable) accessibility point for your consideration. You could have your hyperlinked text in your book open in a new window as opposed to updating the current window so learners aren't having to hit the back button to get back to your site. There are varying opinions on this but it's worth considering whether or not you want someone to have your site up 100% of the time when reading other linked/external resources.

**Comment by mmann1123** [comment]
The opening in a new window is a good idea, but I don't think it can be done with myst markdown. Updated learning objcetives
