### ISSUE TITLE
Creating DOI for citation

### ISSUE THREAD

**Issue by ksuchak1990** [mmann1123/pyGIS#56]
Thanks for making this - it's a very cool resource! I've particularly found some of the hand-drawn illustrations to be really useful.

I was wondering whether you had considered producing a DOI for this (e.g. through Zenodo) to make it easy to cite the book? I had a very quick look and couldn't see anything how to cite it.

**Comment by mmann1123** [comment]
Thanks good recommendation, here is the DOI

https://zenodo.org/badge/latestdoi/344683467
