### ISSUE TITLE
Could you do an example of meteo interpolation using external drift like a DEM? 

### ISSUE THREAD

**Issue by Magio94** [mmann1123/pyGIS#61]
This is the code I am trying to use but is giving me problem for memory allocation
def geodataframe_to_kriging_raster(geodataframe, column_name, pixel_size, area_bounds_gdf, variogram_model="linear"):

    # Check if the two GeoDataFrames have the same coordinate reference system (CRS)
    if geodataframe.crs != area_bounds_gdf.crs:
        # If the CRS is different, change the CRS of one of the GeoDataFrames to match the other
        area_bounds_gdf = area_bounds_gdf.to_crs(geodataframe.crs)
        print('Coordinate reference system modified')

    # Calculate the extent of the GeoDataFrame
    file_bounds = box(*area_bounds_gdf.bounds)

    # Determine the size of the raster based on the extent of the GeoDataFrame
    min_x, min_y, max_x, max_y = file_bounds.bounds
    width = int((max_x - min_x) / pixel_size)
    height = int((max_y - min_y) / pixel_size)

    # Calculate the transformation parameters for the raster
    transform = from_origin(min_x, max_y, pixel_size, pixel_size)

    # Prepare input data
    x = df_hourly['lon'].values
    y = df_hourly['lat'].values
    z = df_hourly[column_name].values

    # Load the DEM (Digital Elevation Model) file
    dem_values = dem.read(1)  # Assume that DEM data is in the first channel
    # Extract x and y coordinates of the DEM
    dem_x, dem_y = dem.bounds.left, dem.bounds.top

    # Perform Universal Kriging with specific drift based on DEM
    h = dem_values
    uk = UniversalKriging(
        x,
        y,
        z,
        variogram_model=variogram_model,
        drift_terms=["external_Z", "specified_drift"],
        external_drift=dem_values,
        external_drift_x=dem_x,
        external_drift_y=dem_y,
        specified_drift=geodataframe['h_sea'],
    )
    z, _ = uk.execute("grid", np.linspace(min_x, max_x, width), np.linspace(max_y, min_y, height))

    return z, transform

**Comment by mmann1123** [comment]
Many of these operations are memory intensive, try using a much larger cell size or limit the extent of your interpolation.

**Comment by Magio94** [comment]
I think the problem could be in the dem. Do you think would it be useful to make a resample of that too? It's 5m resolution >.<

**Comment by mmann1123** [comment]
Yes that is likely an issue. Check how much ram you are using up just reading in the DEM.  Alternatively clip all your files to a smaller area of interest.
