### ISSUE TITLE
Issue on page /docs/d_access_census.html

### ISSUE THREAD

**Issue by oliviasablan** [mmann1123/pyGIS#66]
I am having a problem using "c.acs5.state_county_tract()." I have not had issues using this previously, but just recently I cannot run it. I keep getting this error: "KeyError: 'long'". Is this an issue for other users?

**Comment by mmann1123** [comment]
Can you send a snippet of code so we can see how you are using it?

**Comment by oliviasablan** [comment]
Yes of course. Here is the code: 
`FL_census = c.acs5.state_county_tract(fields = ('NAME', 'B03001_002E', 'B01003_001E',
                                               'B07012_002E', 'C17002_002E', 'C17002_003E', 'B02001_002E'),
                                      state_fips = states.FL.fips,
                                      county_fips = "*", tract = "*", year = 2019)`

I hav also included a screenshot of the error. 
<img width="370" alt="error" src="https://github.com/mmann1123/pyGIS/assets/116751064/85014e6c-b46a-4174-9deb-6a939eb9da08">

**Comment by mmann1123** [comment]
Hmm... I thought i knew what the problem is. But now I am not sure. Can you try running it with a limited number of fields eg `'NAME', 'B03001_002E',`, and see if there is a problem with one of the field codes?  

Are you able to make queries for other times/places fields? For instance try:
``` python 
va_census = c.acs5.state_county_tract(fields = ('NAME', 'C17002_001E', 'C17002_002E', 'C17002_003E', 'B01003_001E'),
                                      state_fips = states.VA.fips,
                                      county_fips = "*",
                                      tract = "*",
                                      year = 2017)
```

Let me know.

**Comment by oliviasablan** [comment]
I've tried both limiting the fields as well as trying a different state. I have also tried using a different year of data (2017 versus 2019), but the error is the same every time.

**Comment by mmann1123** [comment]
Hmm.. is it possible your API key expired?  Try signing up for a new one
https://api.census.gov/data/key_signup.html

**Comment by oliviasablan** [comment]
I thought that may be the case as well, but no luck with a new API. Maybe it's a problem with my conda environment? I was thinking there may be a universal issue with this code, but if it just a problem on my end then I will try digging a little more. Thank you!

**Comment by mmann1123** [comment]
You might open an issue with the census module folks.

Also just to double check, are you putting quotes around your API key eg
"woeinv832fiuf97wgefbv" ?

**Comment by oliviasablan** [comment]
Yes I am! I am not sure why this is happening all of the sudden since I have been using this same code with no changes for months now. I may have installed a new package in the same environment which caused problems with the census package.
